fieldLayouts:
  7c7fa291-8924-4b6d-85c9-d440a436f3d9:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: 08a1c50f-0bab-4592-82b0-226763b90ac6
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 28d445c5-9c5e-4072-84da-5b5dcc0cbcaf
        userCondition: null
fs: local
handle: local
name: local
sortOrder: 1
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: ''
transformSubpath: ''
