version: 0.2
runtime-versions: 
     docker:18.05-dind
phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - aws ecr get-login-password --region eu-west-1 | docker login --username AWS --password-stdin 822603042387.dkr.ecr.eu-west-1.amazonaws.com
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:=latest}

  build:
    commands:
      - apk update
      - apk upgrade
      - apk add python python-dev py2-pip build-base curl gettext
      - pip install docker-compose==1.23.2
      - docker-compose run --rm buildchain yarn run build
      - docker build -f docker-config/php/Dockerfile --pull -t $REPOSITORY_URI-PHP .
      - docker build -f docker-config/nginx/Dockerfile --pull -t $REPOSITORY_URI-NGINX .
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker push $REPOSITORY_URI-PHP:latest
      - docker push $REPOSITORY_URI-NGINX:latest
