version: '2'
services:
  nginx:
      build:
        context: .
        dockerfile: ./docker-config/nginx/Dockerfile
      ports:
          - 80:80
      volumes:
          - cpresources:/var/www/html/web/cpresources
          - ./src/web:/var/www/html/web

  php:
      build:
        context: .
        dockerfile: ./docker-config/php/Dockerfile
      expose:
          - 9000
      volumes:
          - cpresources:/var/www/html/web/cpresources
          - ./src/composer.json:/var/www/html/composer.json
          - ./src/composer.lock:/var/www/html/composer.lock
          - ./src/config:/var/www/html/config
          - ./src/modules:/var/www/html/modules
          - ./src/templates:/var/www/html/templates
          - ./src/web:/var/www/html/web
  buildchain:
      build:
        context: .
        dockerfile: ./docker-config/buildchain/Dockerfile
      volumes:
          - node-modules:/project/node_modules
          - ./docker-config/buildchain/package.json:/project/package.json
          - ./src:/project/src
      command: yarn run watch

      environment:
        ENVIRONMENT: dev
        DB_DRIVER: pgsql
        DB_SERVER: database-2.cluster-cl7j8ehdyvb2.eu-west-1.rds.amazonaws.com
        DB_USER: postgres
        DB_PASSWORD: postgres
        DB_DATABASE: cms
        DB_SCHEMA: public
        DB_TABLE_PREFIX: 
        SITE_URL: http://54.73.135.91
        SECURITY_KEY: agK8M253XwhZ4vH2NnRdrgHmaV4imvQt

  database:
      image: postgres:14.1-alpine
      restart: always
      volumes:
          - db-data:/var/lib/postgresql/data
      ports:
          - 5432:5432
      environment:
          POSTGRES_ROOT_PASSWORD: postgres
          POSTGRES_DATABASE: craft
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres

volumes:
  db-data:
  cpresources:
  node-modules:
